ingest_files:
  description:
    A list of benchmark data files to ingest
  value:
    type: list
    default: []
make_public:
  description: Allow others to use these benchmark datasets?
  value:
    type: choice
    default: true
    choices:
      - true
      - false
