ingest_files:
  description:
    A list of model output files to ingest
  value:
    type: list
    default: []
make_public:
  description: Allow others to use these model outputs?
  value:
    type: choice
    default: true
    choices:
      - true
      - false
